name: "C-Util"
description: "Common Utility Libraries for C11"
avatar: "https://avatars3.githubusercontent.com/u/18634499"
url: "https://c-util.github.io"

baseurl: ""
permalink: "/:title/"
markdown: "kramdown"

footer-links:
  email: "bus1-devel@googlegroups.com"
  github: "c-util"

exclude:
  - AUTHORS
  - LICENSE
  - README
